-- Generated by WISP Game Panel from collection: 3736343437
resource.AddWorkshop("160250458") -- Wiremod
resource.AddWorkshop("3389728250") -- Glide // Styled's Vehicle Base
resource.AddWorkshop("3001397905") -- Media Player Redux
resource.AddWorkshop("3685034437") -- [Z-CITY] Pat's Revamped Punishment
resource.AddWorkshop("3780773397") -- ZСity Gore V2
resource.AddWorkshop("3534116529") -- City 17: Ivaylo Street [v. 2.1] [CSM]
resource.AddWorkshop("3782152589") -- Z-WWE
resource.AddWorkshop("3702088753") -- ZCITY / Surrender
resource.AddWorkshop("3703797859") -- [Z-CITY] EFT Melee Pack
resource.AddWorkshop("3666245817") -- [WFA] WarFighter's Arsenal: ZCity Weapon Pack
resource.AddWorkshop("3703837108") -- WFA Content
resource.AddWorkshop("3694177662") -- Z-City | bib's custom shirts
resource.AddWorkshop("3701366943") -- Z-City | Colorable Clothes + Accessories (Appearance mod)
resource.AddWorkshop("2787722791") -- hmcd_lighthouse
resource.AddWorkshop("3714182343") -- Shootable Door Handles
resource.AddWorkshop("534491717") -- ttt_rooftops_2016
resource.AddWorkshop("3257937532") -- Zcity appearance content
resource.AddWorkshop("3536905594") -- GM_LAKEVIEW
resource.AddWorkshop("3734028848") -- BLIGHTHOUSE
resource.AddWorkshop("3735532784") -- Z-City Horror Additions
resource.AddWorkshop("1762151370") -- Improved FPS Booster
resource.AddWorkshop("3683648045") -- Z-City Chainsaw weapon
resource.AddWorkshop("3284799153") -- TDM City 18
resource.AddWorkshop("3683079310") -- [Z-City] Moodles
resource.AddWorkshop("3750959251") -- MK1 - Homelander
resource.AddWorkshop("950845673") -- Parakeet's Pill Pack
resource.AddWorkshop("3721806933") -- ZCity | Explosive Vest
resource.AddWorkshop("3670522798") -- Z-City Class Changer - Be whoever you want
resource.AddWorkshop("3741271420") -- Z-City | Headcrab Struggle
resource.AddWorkshop("3737422346") -- [Z-CITY] First Spawn Appearance Fix
resource.AddWorkshop("3737887777") -- Z-City [RU/ENG] Bind Menu / Настройка биндов
resource.AddWorkshop("3454674958") -- [TTT] Groverhaus Remastered
resource.AddWorkshop("3709219849") -- Z-City UNCONSCIOUSNESS METER
resource.AddWorkshop("3720595282") -- Homelander SWEP [THE BOYS]
resource.AddWorkshop("3723540354") -- The Boys Base
resource.AddWorkshop("3726268819") -- [Z-City] Civil War
resource.AddWorkshop("3668481858") -- Z-City Appearance Mod
resource.AddWorkshop("3686174019") -- [Z-CITY] Pat's Spectator HUD and Death Recap
resource.AddWorkshop("3721038395") -- mu_smallotown_waste_v2_13
resource.AddWorkshop("3721037390") -- hmcd_metropolis_extended
resource.AddWorkshop("3721036330") -- hmcd_examen
resource.AddWorkshop("3717703126") -- [Z-city] More guns
resource.AddWorkshop("3684466601") -- [Z-CITY] Pat's ULX Commands
resource.AddWorkshop("3709333398") -- ZCITY Player Scale Tool
resource.AddWorkshop("3672748415") -- zb_oldparamenti
resource.AddWorkshop("3330744597") -- Drones | addon [1.8]
resource.AddWorkshop("3684389164") -- [Z-CITY] Pat's Defibrilator
resource.AddWorkshop("3671331409") -- MeleeCity Content (MELEES ONLY)
resource.AddWorkshop("3699477814") -- [Z-City] Extended & Enhanced Ammo Types
resource.AddWorkshop("3695771892") -- [Z-CITY] Spectate ESP
resource.AddWorkshop("3691902281") -- remove content requirements (z-city)
resource.AddWorkshop("3688107233") -- [Z-City] Fury-19
resource.AddWorkshop("3687832222") -- [Z-CITY] Pat's Bear Trap
resource.AddWorkshop("3675753816") -- ZCITY Clothing+
resource.AddWorkshop("2206993805") -- slib - Stromic's Library
resource.AddWorkshop("3685875391") -- [Z-CITY] Pat's Hemostatic Syringe
resource.AddWorkshop("3684346989") -- Pat's Persistent Props
resource.AddWorkshop("3681615626") -- ZCITY Fiber Wire Mod (standalone)
resource.AddWorkshop("3537612611") -- ttt_fernwood
resource.AddWorkshop("3664783005") -- 67th Way Snow | 2022
resource.AddWorkshop("3389795738") -- Glide // GTAV: Helicopters
resource.AddWorkshop("3657166179") -- ttt_scarisland_2026
resource.AddWorkshop("3432497883") -- ttt_warhawk
resource.AddWorkshop("2659980741") -- SmallTown Remake Xmas
resource.AddWorkshop("2701275326") -- Clue XMAS
resource.AddWorkshop("2823321919") -- 67th Way | 2022
resource.AddWorkshop("3322707383") -- gWeather
resource.AddWorkshop("3608909815") -- Port Klax Remastered
resource.AddWorkshop("2403043112") -- Lua Patcher
resource.AddWorkshop("3560775288") -- gm_fork Better
resource.AddWorkshop("3599740510") -- gm_prison
resource.AddWorkshop("3569203772") -- gm_fork_better navmesh and nodegraph
resource.AddWorkshop("3591502168") -- ULX Train Crash Command
resource.AddWorkshop("3578751621") -- GM SecretCamp HMCD
resource.AddWorkshop("531458635") -- Simple Weather
resource.AddWorkshop("3558455765") -- Lark’s Remover – Remove Map Props Permanently
resource.AddWorkshop("3554375309") -- Brutalist McDonald's with fixed spawns and AI nodes
resource.AddWorkshop("2825686616") -- gm_hmcd_rooftops [Sandbox/TTT/Homicide]
resource.AddWorkshop("3491623803") -- zgr_ragcom_highway_valley
resource.AddWorkshop("104607712") -- Extended Properties
resource.AddWorkshop("1620875048") -- Bucket's Optimizations
resource.AddWorkshop("3457317640") -- gm_building_v2 now with war version too.
resource.AddWorkshop("3446456040") -- Distant Shore [ZS]
resource.AddWorkshop("3443920823") -- mu_aughts_v1
resource.AddWorkshop("3441411282") -- Sawdust
resource.AddWorkshop("3434547967") -- gm_broadcasting_station Now with night version.
resource.AddWorkshop("3415635566") -- ttt_diescraper
resource.AddWorkshop("3415418882") -- Restore Position (Context Menu)
resource.AddWorkshop("3407479980") -- BbiCOTKA Remastered
resource.AddWorkshop("3283190993") -- TDM Postbellum
resource.AddWorkshop("3393352147") -- BbiCOTKA Snow
resource.AddWorkshop("3357629647") -- Freeway Thick
resource.AddWorkshop("2249362659") -- TTT Richland Remix
resource.AddWorkshop("3257817980") -- ttt_grovestreet_extended
resource.AddWorkshop("3117864575") -- Keep Decals On Death
resource.AddWorkshop("2264867796") -- Smallotown Remake
resource.AddWorkshop("3271780856") -- Actually Enhanced National Guard
resource.AddWorkshop("3015478782") -- ttt_Waterworld_Tropical
resource.AddWorkshop("3200936715") -- gm_paradise_resort (Pixel Gun 3D Port)
resource.AddWorkshop("2558150898") -- Door Removal Areaportal Fix
resource.AddWorkshop("2082598948") -- zs_adrift (v4)
resource.AddWorkshop("264467687") -- Improved Stacker
resource.AddWorkshop("2716242595") -- 🪄 The Contentalizer!
resource.AddWorkshop("2982286549") -- Server & Client Optimization | FPS Boost
resource.AddWorkshop("2899115076") -- gm_renostruct_v2
resource.AddWorkshop("2937403645") -- ZS Lighthouse Remastered
resource.AddWorkshop("1169579845") -- Fps Booster
resource.AddWorkshop("2907192625") -- Nextbot Navmesh and AI Nodegraph - Iceside
resource.AddWorkshop("2905263284") -- Iceside
resource.AddWorkshop("2827004973") -- [PM] Homelander
resource.AddWorkshop("2807511588") -- ttt_gas_station
resource.AddWorkshop("1873907782") -- Apartments
resource.AddWorkshop("2641379954") -- Hometown 1999 AI Nodes
resource.AddWorkshop("2017098025") -- gm_school
resource.AddWorkshop("2484790252") -- mu_hmcd_mansion
resource.AddWorkshop("718665054") -- Custom ULX Commands
resource.AddWorkshop("2410639636") -- ttt_aircraft
resource.AddWorkshop("2350858257") -- eProtect - Content
resource.AddWorkshop("2251357708") -- [TTT] ttt_ile_v4
resource.AddWorkshop("2188264931") -- ttt_grovestreet_los
resource.AddWorkshop("2000865255") -- Hide ULX & ULib Commands
resource.AddWorkshop("1740863217") -- CrazyRooms
resource.AddWorkshop("1279413779") -- Gm_City17_Apartments
resource.AddWorkshop("855745780") -- Gm_Church
resource.AddWorkshop("1499934731") -- Cabin (zs_cabin_v7)
resource.AddWorkshop("951320281") -- Red gangs players
resource.AddWorkshop("951320773") -- Groove gangs players
resource.AddWorkshop("934024763") -- TTT_CSGOBank
resource.AddWorkshop("510837069") -- cs_drugbust
resource.AddWorkshop("439526795") -- Error Hider
resource.AddWorkshop("286757719") -- Greenwood Estate (Murder)
resource.AddWorkshop("314994389") -- MU_Riverside
resource.AddWorkshop("214144067") -- mu_powerhermit (Murder)
resource.AddWorkshop("268821209") -- ttt_swimming_pool
resource.AddWorkshop("186842624") -- ttt_minecraftcity_v4
resource.AddWorkshop("183797802") -- TTT_island_2013
resource.AddWorkshop("159321088") -- ttt_minecraft_b5
resource.AddWorkshop("107455292") -- HomeTown 1999
resource.AddWorkshop("145316417") -- ttt_fastfood_a6