#!/usr/bin/env python3
"""The one-time cutover (GATE 1) from the legacy live layout to the four built addons the auto-updater manages.

  python3 tools/cutover.py --plan OUT_DIR    write OUT_DIR/CUTOVER.sh, UNDO.sh and CUTOVER.txt
  python3 tools/cutover.py --rehearse        apply the plan to the legacy snapshot from git and check the result

Nothing is deleted. Every legacy path that the built addons (dist/garrysmod/addons/{zcity,ulx,ulib,us1}) now provide
is MOVED to garrysmod/_legacy_us1/<same path>, where Garry's Mod never loads it; UNDO.sh moves it back. The legacy
paths come from manifests/source-map.json (the old tree) plus every addons/us1 file's legacy live path as tools/drop.py
places it (the drops since then). Never moved: data/, cfg/, stock Garry's Mod files (removed-stock-gmod), Workshop and
external vendor folders, and garrysmod/addons/{zcity,ulx,ulib,us1} themselves, which the updater swaps whole.
Run CUTOVER.sh from the server root (the folder holding garrysmod/) with the server stopped, then run us1_update.sh.
"""
import argparse, json, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import drop  # noqa: E402  (live_target, upstream_outputs: the one legacy path mapping)

KEEP = {"vendor-workshop", "vendor-external", "removed-stock-gmod"}
MANAGED = ("zcity", "ulx", "ulib", "us1")
PARK = "garrysmod/_legacy_us1/"
SNAPSHOT = "e7f1b5a"  # the last commit of the legacy tree (docs/MIGRATION.md)


def git(*a):
    return subprocess.run(["git", *a], cwd=ROOT, check=True, capture_output=True, text=True).stdout


def managed(p):
    return any(p.startswith(f"garrysmod/addons/{n}/") for n in MANAGED)


def legacy_paths():
    """Sorted live paths to park."""
    smap = json.loads((ROOT / "manifests/source-map.json").read_text())["files"]
    out = set()
    for r in smap:
        if r["disposition"].split(":")[0] in KEEP:
            continue
        old = r["old"]
        if old.startswith("garrysmod/") and not managed(old) and not old.startswith(("garrysmod/data/", "garrysmod/cfg/")):
            out.add(old)
    new_to_old = {r["new"]: r["old"] for r in smap if r.get("new")}
    outputs = drop.upstream_outputs()
    # every addons/us1 path that has existed since the snapshot (current and deleted): drops put each at this path
    names = set(git("log", "--format=", "--name-only", f"{SNAPSHOT}..HEAD", "--", "addons/us1").split())
    for p in sorted(names):
        target, _ = drop.live_target(p, new_to_old, outputs)
        if target and not managed(target):
            out.add(target)
    return sorted(out)


def q(s):
    return "'" + s.replace("'", "'\\''") + "'"


def plan(out_dir):
    paths = legacy_paths()
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    head = ["#!/bin/sh", "# generated by tools/cutover.py: run from the server root with the server STOPPED", "set -u",
            '[ -d garrysmod ] || { echo "run this from the folder that holds garrysmod/"; exit 1; }', "n=0"]
    go, undo = list(head), list(head)
    for p in paths:
        dest = PARK + p[len("garrysmod/"):]
        go.append(f'[ -e {q(p)} ] && mkdir -p {q(str(Path(dest).parent))} && mv {q(p)} {q(dest)} && n=$((n+1))')
        undo.append(f'[ -e {q(dest)} ] && mkdir -p {q(str(Path(p).parent))} && mv {q(dest)} {q(p)} && n=$((n+1))')
    go.append('echo "moved $n legacy files into garrysmod/_legacy_us1/ (UNDO.sh puts them back)"')
    undo.append('echo "restored $n legacy files"')
    (out / "CUTOVER.sh").write_text("\n".join(go) + "\n")
    (out / "UNDO.sh").write_text("\n".join(undo) + "\n")
    (out / "CUTOVER.txt").write_text("\n".join(paths) + "\n")
    print(f"{len(paths)} legacy paths -> {out}/CUTOVER.sh (UNDO.sh, CUTOVER.txt)")
    return paths


def lua_virtual(tree):
    """{virtual lua path: [providers]} across garrysmod/lua and garrysmod/addons/*/lua (plus gamemodes)."""
    seen = {}
    g = tree / "garrysmod"
    roots = [("lua", g / "lua"), ("gamemodes", g / "gamemodes")]
    for a in sorted((g / "addons").iterdir()) if (g / "addons").is_dir() else []:
        roots += [("lua", a / "lua"), ("gamemodes", a / "gamemodes")]
    for kind, base in roots:
        if not base.is_dir():
            continue
        for f in base.rglob("*"):
            if f.is_file():
                seen.setdefault(f"{kind}/{f.relative_to(base).as_posix()}", []).append(str(base.relative_to(tree)))
    return seen


def rehearse():
    dist = ROOT / "dist/garrysmod/addons"
    if not all((dist / n).is_dir() for n in MANAGED):
        sys.exit("run tools/build.py first")
    with tempfile.TemporaryDirectory() as tmp:
        tree = Path(tmp) / "server"
        tree.mkdir()
        tar = subprocess.run(["git", "archive", SNAPSHOT, "garrysmod"], cwd=ROOT, check=True, capture_output=True).stdout
        subprocess.run(["tar", "-x", "-C", str(tree)], input=tar, check=True)
        # the drops since the snapshot: every current addons/us1 file at its legacy path
        smap = json.loads((ROOT / "manifests/source-map.json").read_text())["files"]
        new_to_old = {r["new"]: r["old"] for r in smap if r.get("new")}
        for p in git("ls-files", "addons/us1").split("\n"):
            t, src = drop.live_target(p, new_to_old, drop.upstream_outputs()) if p else (None, None)
            if t and not managed(t):
                (tree / t).parent.mkdir(parents=True, exist_ok=True)
                (tree / t).write_bytes((ROOT / src).read_bytes())
        plan(Path(tmp) / "plan")
        r = subprocess.run(["sh", str(Path(tmp) / "plan/CUTOVER.sh")], cwd=tree, capture_output=True, text=True)
        print("  " + r.stdout.strip())
        # what the updater then does: the four managed folders replaced by the build
        import shutil
        for n in MANAGED:
            shutil.rmtree(tree / "garrysmod/addons" / n, ignore_errors=True)
            shutil.copytree(dist / n, tree / "garrysmod/addons" / n)
        got = lua_virtual(tree)
        want = lua_virtual(ROOT / "dist")
        missing = sorted(set(want) - set(got))
        twice = sorted(p for p, who in got.items() if len(who) > 1 and not p.endswith((".md", ".txt", ".json")))
        extra = sorted(p for p, who in got.items() if p not in want and p.endswith(".lua")
                       and not any(w in ("garrysmod/lua", "garrysmod/gamemodes") for w in who))
        print(f"  lua paths after cutover: {len(got)}; built addons provide {len(want)}")
        for label, rows in (("missing", missing), ("provided twice", twice), ("left in other addon folders", extra)):
            print(f"  {label}: {len(rows)}")
            for p in rows[:15]:
                print(f"    {p}  ({', '.join(got.get(p, []))})")
        return 0 if not missing and not twice else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--plan", metavar="OUT_DIR")
    g.add_argument("--rehearse", action="store_true")
    a = ap.parse_args()
    if a.plan:
        plan(a.plan)
        return 0
    return rehearse()


if __name__ == "__main__":
    sys.exit(main())
